### ISSUE TITLE
undefined method `file=' for #<Pry::History` using pry v0.13

### ISSUE THREAD

**Issue by johnpaulashenfelter** [guard/guard#956] opened 2020-03-22 22:59 UTC
Using the latest version of guard and pry (just released) in a Rails application, you'll get this error:

```
$ bundle exec guard

18:56:59 - INFO - Bye bye...
/Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard/jobs/pry_wrapper.rb:131:in `_setup': undefined method `file=' for #<Pry::History:0x00007fd6b59ed778> (NoMethodError)
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard/jobs/pry_wrapper.rb:68:in `initialize'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard/interactor.rb:17:in `new'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard/interactor.rb:17:in `initialize'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard.rb:67:in `new'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard.rb:67:in `setup'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard/commander.rb:32:in `start'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard/cli/environments/valid.rb:16:in `start_guard'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard/cli.rb:122:in `start'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard/aruba_adapter.rb:32:in `execute'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/lib/guard/aruba_adapter.rb:19:in `execute!'
	from /Users/johnpaul/me/gobbol/.bundle/ruby/2.6.0/gems/guard-2.16.1/bin/_guard-core:11:in `<main>'
```

There's a PR that fixes this already submitted #955 

In the meantime, you can lock your version of `pry` to v0.12 in your Gemfile
```
  gem 'pry', '< 0.13' # or maybe just '0.12.2'
```

These versions work:

```
 * guard (2.16.1)
 * pry (0.12.2)
 * pry-byebug (3.8.0)
 * pry-rails (0.3.9)
```

while this set will now

```
 * guard (2.16.1)
 * pry (0.13)
 * pry-byebug (3.9.0)
 * pry-rails (0.3.9)
```

**Comment by johnpaulashenfelter** [comment] 2020-03-22 23:01
A more complete diff of the Gemfile.lock

```
-    method_source (0.9.2)
+    method_source (1.0.0)
     mimemagic (0.3.4)
     mini_mime (1.0.2)
     mini_portile2 (2.4.0)
@@ -165,12 +165,12 @@ GEM
     parser (2.7.0.5)
       ast (~> 2.4.0)
     pg (1.2.3)
-    pry (0.12.2)
-      coderay (~> 1.1.0)
-      method_source (~> 0.9.0)
-    pry-byebug (3.8.0)
+    pry (0.13.0)
+      coderay (~> 1.1)
+      method_source (~> 1.0)
+    pry-byebug (3.9.0)
       byebug (~> 11.0)
-      pry (~> 0.10)
+      pry (~> 0.13.0)
```

**Comment by rymai** [comment] 2020-03-23 08:19
I think this is a duplicate of https://github.com/guard/guard/issues/953. Thanks for the issue anyway!

**Closed by rymai** 2020-03-23 08:19 UTC
