### ISSUE TITLE
`validate_and_sanitize_new_state': Listen::Listener can't change state from 'backend_started' to 'stopped', only to: frontend_ready

### ISSUE THREAD

**Issue by jinleileiking** [guard/guard#822] opened 2016-04-08 10:27 UTC
```
18:26:49 - INFO - Guard::Minitest 2.4.4 is running, with Minitest::Unit 5.4.3!
18:26:49 - INFO - Running: all tests
Run options: --seed 20199

# Running:



Finished in 0.000771s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips

/home/users/jinlei04/.jumbo/lib/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/fsm.rb:76:in `validate_and_sanitize_new_state': Listen::Listener can't change state from 'backend_started' to 'stopped', only to: frontend_ready (ArgumentError)
        from /home/users/jinlei04/.jumbo/lib/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/fsm.rb:55:in `transition'
        from /home/users/jinlei04/.jumbo/lib/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/listener.rb:98:in `stop'
        from /home/users/jinlei04/.jumbo/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:48:in `ensure in execute'
        from /home/users/jinlei04/.jumbo/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:56:in `execute'
        from /home/users/jinlei04/.jumbo/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:19:in `execute!'
        from /home/users/jinlei04/.jumbo/lib/ruby/gems/2.2.0/gems/guard-2.13.0/bin/_guard-core:11:in `<main>'
```

**Comment by e2** [comment] 2016-04-08 20:09
I understand what's wrong. I think I can fix it. But I can't reproduce this myself.

Can you share a simple repository producing this error? I just want to make sure it's fixed properly.

**Comment by 1v** [comment] 2016-04-30 11:51
Same error on startup:

```
11:34:46 - INFO - Guard::RSpec is running
FATAL: Listen error: unable to monitor directories for changes.
Visit https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for info on how to fix this.
/home/luna/.rvm/gems/ruby-2.3.0/gems/listen-3.0.6/lib/listen/fsm.rb:76:in `validate_and_sanitize_new_state': Listen::Listener can't change state from 'backend_started' to 'stopped', only to: frontend_ready (ArgumentError)
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/listen-3.0.6/lib/listen/fsm.rb:55:in `transition'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/listen-3.0.6/lib/listen/listener.rb:98:in `stop'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:48:in `execute'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:19:in `execute!'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/guard-2.13.0/bin/_guard-core:11:in `<main>'
```

I can't increase watchers because I'm on VPS.

```
$ cat /proc/sys/fs/inotify/max_user_watches
8192
$ sudo sysctl fs.inotify.max_user_watches=524288
sysctl: permission denied on key 'fs.inotify.max_user_watches'
```
Other app with same Guardfile is working without any errors.

```
guard :rspec, cmd: "bundle exec rspec" do
  watch(%r{^(app|spec|config|lib)/(.+)}) { "spec" }
end
```

**Comment by 1v** [comment] 2016-04-30 12:17
One-liner to reproduce:

```
mkdir -p {01..10}/{01..10}/{01..10}/{01..10} && guard init && guard
```

**Comment by e2** [comment] 2016-04-30 14:45
Thanks, @1v - that was enough for me to properly test and fix this.

Will be released soon. (for both Listen 3.1 and 3.0).

**Closed** 2016-04-30 19:44 UTC

**Comment by e2** [comment] 2016-04-30 19:56
Released in 3.1.2:  https://github.com/guard/listen/releases/tag/v3.1.2
Released in 3.0.7 (backport) : https://github.com/guard/listen/releases/tag/v3.0.7

@1v - you'll still get the error from watching more directories than INotify allows you. You can either:
- watch less directories (see guard `directories` option)
- use polling
- use symlinks to an outside directory

**Comment by 1v** [comment] 2016-05-02 17:26
I excluded some dirs like that:

```
 bundle exec guard -w `find . -maxdepth 1 -type d -not -path "./tmp" -not -path "./public" -not -path "./.git" -not -path "./log" -not -path "."`
```

**Comment by e2** [comment] 2016-05-02 18:29
I think ignored directories in Guard shouldn't be watched by default (if possible): https://github.com/guard/guard/issues/829
