### ISSUE TITLE
Command execution: stty  2>/dev/null

### ISSUE THREAD

**Issue by peterokagey** [guard/guard#736] opened 2015-02-07 21:34 UTC
The only other place where I've seen something similar is: https://github.com/guard/guard/issues/664, but I'm not using minitest here.

```
math (master) $ bundle exec guard -d
13:25:52 - DEBUG - Command execution: emacsclient --eval '1'
13:25:52 - DEBUG - Notiffany: emacs not available (Emacs client failed).
13:25:52 - DEBUG - Notiffany: tmux not available (:tmux notifier is only available inside a TMux session.).
13:25:52 - DEBUG - Notiffany: file not available (No :path option given).
13:25:52 - DEBUG - Notiffany is using GNTP to send notifications.
13:25:52 - DEBUG - Notiffany is using TerminalTitle to send notifications.
13:25:52 - DEBUG - Command execution: hash stty
13:25:52 - DEBUG - Guard starts all plugins
13:25:52 - DEBUG - Hook :start_begin executed for Guard::RSpec
13:25:52 - INFO - Guard::RSpec is running
13:25:52 - DEBUG - Hook :start_end executed for Guard::RSpec
13:25:52 - INFO - Guard is now watching at '/Users/pkagey/personal/math'
13:25:52 - DEBUG - Start interactor
13:25:52 - DEBUG - Command execution: stty -g 2>/dev/null
13:25:57 - DEBUG - Interactor was stopped or killed
13:25:57 - DEBUG - Command execution: stty  2>/dev/null
```

If I save ```OEIS/specs/a006255_spec.rb``` my test is not run, but the terminal reads:
```
"OEIS/specs/a006255_spec.rb"
13:25:57 - DEBUG - Hook :run_on_modifications_begin executed for Guard::RSpec
13:25:57 - DEBUG - Hook :run_on_modifications_end executed for Guard::RSpec
13:25:57 - DEBUG - Start interactor
13:25:57 - DEBUG - Command execution: stty -g 2>/dev/null
```

If I run ```all```, I get:
```
[1] guard(main)> all
13:31:38 - DEBUG - Interactor was stopped or killed
13:31:38 - DEBUG - Command execution: stty  2>/dev/null
13:31:38 - INFO - Run all
13:31:38 - DEBUG - Hook :run_all_begin executed for Guard::RSpec
13:31:38 - INFO - Running all specs
13:31:38 - ERROR - No cmd option specified, unable to run specs!
13:31:38 - ERROR - Guard::RSpec failed to achieve its <run_all>, exception was:
> [#69C01E12DE1B] Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 23053
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_gntp-0.3.4/lib/ruby_gntp.rb:155:in `initialize'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_gntp-0.3.4/lib/ruby_gntp.rb:155:in `open'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_gntp-0.3.4/lib/ruby_gntp.rb:155:in `send_and_recieve'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_gntp-0.3.4/lib/ruby_gntp.rb:90:in `register'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/notiffany-0.0.4/lib/notiffany/notifier/gntp.rb:77:in `_gntp_client'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/notiffany-0.0.4/lib/notiffany/notifier/gntp.rb:63:in `_perform_notify'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/notiffany-0.0.4/lib/notiffany/notifier/base.rb:72:in `notify'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/notiffany-0.0.4/lib/notiffany/notifier.rb:183:in `block in notify'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/notiffany-0.0.4/lib/notiffany/notifier.rb:182:in `each'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/notiffany-0.0.4/lib/notiffany/notifier.rb:182:in `notify'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/notifier.rb:33:in `notify'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-compat-1.2.1/lib/guard/compat/plugin.rb:113:in `notify'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-rspec-4.5.0/lib/guard/rspec/notifier.rb:23:in `notify_failure'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-rspec-4.5.0/lib/guard/rspec/runner.rb:60:in `_cmd_option_present'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-rspec-4.5.0/lib/guard/rspec/runner.rb:41:in `_run'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-rspec-4.5.0/lib/guard/rspec/runner.rb:24:in `run_all'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-rspec-4.5.0/lib/guard/rspec.rb:33:in `block in run_all'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-rspec-4.5.0/lib/guard/rspec.rb:48:in `_throw_if_failed'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-rspec-4.5.0/lib/guard/rspec.rb:33:in `run_all'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:82:in `block in _supervise'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:79:in `catch'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:79:in `_supervise'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:22:in `block (3 levels) in run'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:119:in `block (2 levels) in _run_group_plugins'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:117:in `each'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:117:in `block in _run_group_plugins'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:116:in `catch'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:116:in `_run_group_plugins'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:21:in `block (2 levels) in run'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:20:in `each'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:20:in `block in run'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/lumberjack-1.0.9/lib/lumberjack.rb:32:in `unit_of_work'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/runner.rb:18:in `run'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/commander.rb:82:in `run_all'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/internals/queue.rb:42:in `block in _run_actions'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/internals/queue.rb:37:in `each'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/internals/queue.rb:37:in `_run_actions'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/internals/queue.rb:21:in `process'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/commander.rb:43:in `start'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/cli.rb:113:in `start'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/aruba_adapter.rb:32:in `execute'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-2.11.1/bin/guard:11:in `<top (required)>'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/bin/guard:23:in `load'
> [#69C01E12DE1B] /Users/pkagey/.rbenv/versions/2.1.5/bin/guard:23:in `<main>'
13:31:38 - INFO - Guard::RSpec has just been fired
13:31:38 - DEBUG - Start interactor
13:31:38 - DEBUG - Command execution: stty -g 2>/dev/null
```

My Gemfile looks like this:
```
source "https://rubygems.org"

group :development do
  gem "rspec"
  gem 'guard-rspec', require: false
  gem 'ruby_gntp'
  gem 'growl'
end
```

My Guardfile looks like this: 
```
guard :rspec do
  watch(%r{^OEIS/specs/(.+)_spec\.rb$}) do |m|
    p "OEIS/specs/#{m[1]}_spec.rb"
    "OEIS/specs/#{m[1]}_spec.rb"
  end

  watch(%r{^OEIS/scripts/(.+)\.rb$}) do |m|
    p "OEIS/specs/#{m[1]}_spec.rb"
    "OEIS/specs/#{m[1]}_spec.rb"
  end
  watch('spec/spec_helper.rb')  { "spec" }
end
```

Any thoughts?

**Comment by peterokagey** [comment] 2015-02-07 21:36
```
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using coderay 1.1.0
Using diff-lcs 1.2.5
Using ffi 1.9.6
Using formatador 0.2.5
Using growl 1.0.3
Using rb-fsevent 0.9.4
Using rb-inotify 0.9.5
Using listen 2.8.5
Using lumberjack 1.0.9
Using nenv 0.2.0
Using shellany 0.0.1
Using notiffany 0.0.4
Using method_source 0.8.2
Using slop 3.6.0
Using pry 0.10.1
Using thor 0.19.1
Using guard 2.11.1
Using guard-compat 1.2.1
Using rspec-support 3.2.1
Using rspec-core 3.2.0
Using rspec-expectations 3.2.0
Using rspec-mocks 3.2.0
Using rspec 3.2.0
Using guard-rspec 4.5.0
Using ruby_gntp 0.3.4
Using bundler 1.7.12
```

**Comment by e2** [comment] 2015-02-08 00:34
> "OEIS/specs/a006255_spec.rb"
This means the file was matched, which is a great way to debug :+1: 

> 13:25:57 - DEBUG - Hook :run_on_modifications_begin executed for Guard::RSpec
This means guard-rspec was called because there was a matching file.

> 13:25:57 - DEBUG - Hook :run_on_modifications_end executed for Guard::RSpec
This means guard-rspec succesfully ended - but if no tests were run, it's probably a bug in Guard::RSpec.

The layout is non-standard (OEIS/specs), so that might be a cause.

Could you setup a minimal new repo that reproduces the problem? (You don't have to open an issue in Guard::RSpec - I'll do that). 

If you do, I'll probably find the cause quickly and fix it + release a fix (I prefer a repo to reproduce this, just so I can 100% confirm it's fixed in your scenario).

**Comment by e2** [comment] 2015-02-08 00:37
As for:

> Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 23053

That's just because Guard detected that GNTP is available, but it doesn't seem to be running.

Notiffany is using GNTP to send notifications.

You could just turn of notifications for now, or configure them in your `~/.guard.rb` file, like mentioned here: https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard#notification

**Comment by e2** [comment] 2015-02-08 00:43
Oh, and the `stty 2>/dev/null` is harmless - it's just to reset the terminal in case a plugin screws up the colors.

There are 2 different issues here:
1. guard-rspec doesn't seem to want to run your test (again, just setup a simple repo to reproduce this, and I'll take over)
2. notiffany doesn't want to work with default settings (maybe you just need to properly configure gntp - with a proper ip/port and password). (again, either configure gntp, configure your own notifiers, or turn them off)

**Comment by peterokagey** [comment] 2015-02-08 02:23
Cezary,
Thanks for your help! I've pushed my repo with the bug to: https://github.com/PeterKagey/math.

I don't care about GNTP. I only installed it because something in the logs had mentioned it.

I'm running OSX 10.10.1. As far as I can tell, it is unrelated to this issue, however: https://github.com/guard/guard/wiki/Add-Readline-support-to-Ruby-on-Mac-OS-X.

**Comment by e2** [comment] 2015-02-08 11:44
There's actually a special option to set custom spec dirs (see guard-rspec README). 

Also, you'll need 'bundle exec rspec' for newer versions of guard-rspec (it's best to run guard using `bundle exec`).

Here's the fixed Guardfile:
```ruby
guard :rspec, cmd: 'bundle exec rspec', spec_paths: ['OEIS/specs'] do
  watch(%r{^OEIS/specs/(.+)_spec\.rb$}) { |m| "OEIS/specs/#{m[1]}_spec.rb" }
  watch(%r{^OEIS/scripts/(.+)\.rb$}) { |m| "OEIS/specs/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }
end
```

**Closed by e2** 2015-02-08 11:44 UTC
