### ISSUE TITLE
Guard pegging CPU on Big Sur

### ISSUE THREAD

**Issue by henryaj** [guard/guard#967] opened 2020-12-17 17:47 UTC
Running `guard` on Big Sur on an M1 MacBook Air, I'm seeing a whole CPU core get pegged by the process (98% CPU usage or so). I've also seen [something similar happening with spring](https://github.com/rails/spring/issues/636) so am wondering if there's an issue with the way file watches are done on Big Sur.

Anyone have any ideas on how to best to debug this? Thanks!

**Comment by raldred** [comment] 2021-01-06 16:00
Seeing this too, possibly caused by the listen gem. Which falls back to polling if you're running a version without this fix:
https://github.com/guard/listen/issues/478

**Comment by rymai** [comment] 2021-01-06 16:10
Indeed, this was fixed and released as part of https://github.com/guard/listen/releases/tag/v3.3.0.

**Closed by rymai** 2021-01-06 16:10 UTC
