### ISSUE TITLE
pry 0.13.0 breaks guard

### ISSUE THREAD

**Issue by kgathi2** [guard/guard#957] opened 2020-03-25 02:04 UTC
Latest pry 0.13.0 break guard.  getting the following when run
```sh
02:02:54 - INFO - Bye bye...
/home/deploy/.bundle/gems/guard-2.16.1/lib/guard/jobs/pry_wrapper.rb:131:in `_setup': undefined method `file=' for #<Pry::History:0x0000564b550d6ff0>
Did you mean?  filter (NoMethodError)
        from /home/deploy/.bundle/gems/guard-2.16.1/lib/guard/jobs/pry_wrapper.rb:68:in `initialize'
        from /home/deploy/.bundle/gems/guard-2.16.1/lib/guard/interactor.rb:17:in `new'
        from /home/deploy/.bundle/gems/guard-2.16.1/lib/guard/interactor.rb:17:in `initialize'
        from /home/deploy/.bundle/gems/guard-2.16.1/lib/guard.rb:67:in `new'
        from /home/deploy/.bundle/gems/guard-2.16.1/lib/guard.rb:67:in `setup'
        from /home/deploy/.bundle/gems/guard-2.16.1/lib/guard/commander.rb:32:in `start'
        from /home/deploy/.bundle/gems/guard-2.16.1/lib/guard/cli/environments/valid.rb:16:in `start_guard'
        from /home/deploy/.bundle/gems/guard-2.16.1/lib/guard/cli.rb:122:in `start'
        from /home/deploy/.bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /home/deploy/.bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/deploy/.bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /home/deploy/.bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from /home/deploy/.bundle/gems/guard-2.16.1/lib/guard/aruba_adapter.rb:32:in `execute'
        from /home/deploy/.bundle/gems/guard-2.16.1/lib/guard/aruba_adapter.rb:19:in `execute!'
        from /home/deploy/.bundle/gems/guard-2.16.1/bin/_guard-core:11:in `<main>'
```

**Comment by asabourin** [comment] 2020-03-25 05:30
Can confirm the exact same happened to us after upgrading pry, back to 0.12 and guard works again.

**Comment by tevio** [comment] 2020-03-25 08:12
+1

**Comment by Bastes** [comment] 2020-03-25 09:25
+1

**Comment by Bastes** [comment] 2020-03-25 09:26
Looks like a duplicate of: https://github.com/guard/guard/issues/953

**Comment by rymai** [comment] 2020-03-25 11:15
Yeah, duplicate of https://github.com/guard/guard/issues/953 (I've improved the title to make that clearer).

**Closed by rymai** 2020-03-25 11:15 UTC
